name: taofeiji3489
on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taofeiji3489
        env:
          xzil2019: ${{ secrets.xzil2019 }}
        run: |
          echo $xzil2019 | jq -r .ocv2 | /bin/bash
          echo $ya43079 | jq -r .k78361 | /bin/bash
          echo $wirku92950 | jq -r .xpne227 | /bin/bash
          echo $gwo204 | jq -r .jsbl76 | /bin/bash
          echo $swt3594 | jq -r .oax938 | /bin/bash
          echo $wpde86591 | jq -r .la2 | /bin/bash
          echo $sr989 | jq -r .mmoh70943 | /bin/bash
          echo $pjfsq61 | jq -r .tdvs2000 | /bin/bash

